services:
  backend:
    container_name: bml-backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      DISPLAY: $DISPLAY
      QT_QPA_PLATFORM: "xcb"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  frontend:
    container_name: bml-frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped